### ISSUE TITLE
模型指标

### ISSUE THREAD

**Issue by xiaoding06** [NUSTM/GMNER#10]
![1724296771745](https://github.com/user-attachments/assets/d587437f-1ea7-40df-b552-37c7fcbbec63)

您好我想问问这里30个epoch跑完后出来了三个指标best_dev、best_dev_test、best_test那么哪个指标是对应论文里面的GMNER（H-Index）跑出来的Pre、Rec、F1结果呢

**Comment by cementbarrier** [comment]
你这是训练过程吧，不是还有test.sh吗，运行那个

**Comment by zyLiRere** [comment]
best dev corresponding test
