### ISSUE TITLE
代码咨询

### ISSUE THREAD

**Issue by APPLE-XMT** [NUSTM/GMNER#2]
您好，我在运行您代码的时候出现了这个问题，请问是为什么呢？ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**Comment by zyLiRere** [comment]
您好，抱歉没有及时回复。我运行我的代码时没有遇到这个报错。希望您提供更多的相关信息，例如报错位置和您使用的环境等，我将尽可能尝试解决。

**Comment by APPLE-XMT** [comment]
谢谢，这个我解决了

**Comment by 10652835** [comment]
我也遇到了这个问题，请问是怎么解决的啊？

**Comment by APPLE-XMT** [comment]
> 我也遇到了这个问题，请问是怎么解决的啊？

你找找你报错提示的地方，我记得是改了一个库里面的文件，将nd.arrary删掉，具体是哪里我有点忘记了，报错原因好像是数据长短不一致，所以会报错

**Comment by 10652835** [comment]
谢谢，我刚刚试了试降级一下numpy==1.23.1解决了这个问题，仅供大家参考

**Comment by HuilongYu** [comment]
我numpy版本改为1.23.5能行
