### ISSUE TITLE
提取图片特征

### ISSUE THREAD

**Issue by APPLE-XMT** [NUSTM/GMNER#3]
您好，请问可以提供一下提取图片特征的代码吗？

**Comment by zyLiRere** [comment]
您可以通过以下URL访问我们通过VinVL抽取的candidate feature：https://pan.baidu.com/s/1QqjOlAAjCqAk_qL6ejeARw?pwd=TwVi (提取码：TwVi)。需要注意的是，这些是来自Twitter 2015和Twitter 2017数据集的结果，您可以通过图片ID链接到相应的candidate。

**Comment by APPLE-XMT** [comment]
您好，我是想在您的代码上应用其它的数据集，但我用vinvl提取的特征运行代码时，train_region_loss一直为0，我想请问一下您可以提供一下您提取图片特征的代码吗？

**Comment by APPLE-XMT** [comment]
请问您在训练过程中会遇到f1、rec、pre指标一直为0的情况吗？

**Comment by stepjames1998** [comment]
> 您可以通过以下URL访问我们通过VinVL抽取的candidate feature：https://pan.baidu.com/s/1QqjOlAAjCqAk_qL6ejeARw?pwd=TwVi (提取码：TwVi)。需要注意的是，这些是来自Twitter 2015和Twitter 2017数据集的结果，您可以通过图片ID链接到相应的candidate。

您好，非常好的工作，我想请问一下是否可以提供一下Vinvl抽取出来的子图片呢？我们想基于图片本身做一些额外的研究？

**Comment by zyLiRere** [comment]
> 请问您在训练过程中会遇到f1、rec、pre指标一直为0的情况吗？

在我们的训练过程中，我们目前尚未遇到过这种情况。

**Comment by stepjames1998** [comment]
你好，我这儿还有个小问题，仓库里的代码跑出来预测指标只有一个，看起来是GMNER的指标，是否能增加一下其他两个指标的计算呢？

**Comment by zyLiRere** [comment]
> > 您可以通过以下URL访问我们通过VinVL抽取的candidate feature：https://pan.baidu.com/s/1QqjOlAAjCqAk_qL6ejeARw?pwd=TwVi (提取码：TwVi)。需要注意的是，这些是来自Twitter 2015和Twitter 2017数据集的结果，您可以通过图片ID链接到相应的candidate。
> 
> 您好，非常好的工作，我想请问一下是否可以提供一下Vinvl抽取出来的子图片呢？我们想基于图片本身做一些额外的研究？

您好，感谢您的关注。对于VinVL目标检测结果的子图像，可以通过以上给出的VinVL results裁剪原始图片得到cropped_image，以下是一个简单的实现，您可以参考。

```
  import os
  from PIL import Image
  import numpy as np
  
  img_path_vinvl = 'vinvl_results_path'
  img_path = 'raw_images_path'
  
  img_id_list = []
  
  output_directory = "output_images_path"
  os.makedirs(output_directory, exist_ok=True)
  
  for root, dirs, files in os.walk(img_path):
      img_id_list = files
  
  for img_id in img_id_list:
      try:
          img = np.load(os.path.join(img_path_vinvl, img_id + '.npz'))
      except FileNotFoundError:
          continue
          
      bounding_boxes = img['bounding_boxes']
      scores = img['scores']
      objects = img['objects']
  
      raw_image = Image.open(os.path.join(img_path, img_id))
      for i, (bbox, score, object) in enumerate(zip(bounding_boxes, scores, objects)):
          left, top, right, bottom = bbox
          
          cropped_image = raw_image.crop((left, top, right, bottom))
          output_filename = os.path.join(output_directory, f"{img_id[:-4]}_cropped_image_{i}_score_{score}_object_{object}.jpg")
          cropped_image.save(output_filename)
  ```

**Comment by zyLiRere** [comment]
> 你好，我这儿还有个小问题，仓库里的代码跑出来预测指标只有一个，看起来是GMNER的指标，是否能增加一下其他两个指标的计算呢？

您好，我们目前的代码中仅包含了GMNER的指标计算，这是因为在训练模型时，我们没有考虑MNER和EEG这两个指标，因此它们没有在代码中实现。

如果您希望计算MNER和EEG指标，您可以在代码的"model.metrics"文件中进行修改。

**Comment by stepjames1998** [comment]
> > 你好，我这儿还有个小问题，仓库里的代码跑出来预测指标只有一个，看起来是GMNER的指标，是否能增加一下其他两个指标的计算呢？
> 
> 您好，我们目前的代码中仅包含了GMNER的指标计算，这是因为在训练模型时，我们没有考虑MNER和EEG这两个指标，因此它们没有在代码中实现。
> 
> 如果您希望计算MNER和EEG指标，您可以在代码的"model.metrics"文件中进行修改。

好的，非常感谢！
