### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (32,) + inhomogeneous part.

### ISSUE THREAD

**Issue by lxystaruni** [NUSTM/GMNER#8]
您好，我在复现您的代码时遇到了下面这个问题：
<img width="862" alt="屏幕截图 2024-05-21 200439" src="https://github.com/NUSTM/GMNER/assets/126388216/60b8984a-5da1-4658-aab9-0b25d3fe9677">
我猜测这个错误是尝试将形状不一致的序列合并到一个 numpy 数组导致的，但我不知道如何解决这个问题。
不知您是否可以帮我解决这个问题？非常感谢！

**Comment by zyLiRere** [comment]
https://github.com/NUSTM/GMNER/issues/2#issue-1868431242

看到之前好像已经有类似的问题已被解决，您可以尝试一下

**Comment by lxystaruni** [comment]
谢谢！将numpy降级为1.23.1，可以解决这个问题
